spring:
  datasource:
    url: jdbc:postgresql://10.11.0.134:5432/postgres
    username: postgres
    password: motor123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  profiles:
    active: dev

server:
  port: 9090
