server:
  port: 8888

## REF: https://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.1.3.RELEASE/
#############    Local resources   ################
spring:
  profiles:
     active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/

#############    Git repo resources   ################
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Destroy-Youth/config-repo.git
#          clone-on-start: true
